# Generated by Django 4.1.5 on 2023-01-19 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_category_listings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='listings',
            new_name='Listing',
        ),
    ]
